### ISSUE TITLE
Web App / Azure - 404 error under deployment center

### ISSUE THREAD

**Issue by Adam-McGill** [liatrio/terraform-azure-github-runner#114]
I have deployed the instance with the module, setup the github app and kv secrets for github.  The VMs are being created, no runners are showing up in GitHub.  Reviewing the deployment center I see the following error, do you know what I should be looking for here on what is generating the 404?  Thanks,

2024_08_02_lw0sdlwk000019_default_docker.log:
2024-08-02T18:22:35.800866145Z /usr/src/app/node_modules/@azure/core-http/dist/index.js:3159
2024-08-02T18:22:35.800935247Z const error = new RestError(initialErrorMessage, undefined, parsedResponse.status, parsedResponse.request, parsedResponse);
2024-08-02T18:22:35.800943447Z ^
2024-08-02T18:22:35.800947547Z
2024-08-02T18:22:35.800951147Z RestError
2024-08-02T18:22:35.800954747Z at handleErrorResponse (/usr/src/app/node_modules/@azure/core-http/dist/index.js:3159:19)
2024-08-02T18:22:35.800958847Z at /usr/src/app/node_modules/@azure/core-http/dist/index.js:3095:49
2024-08-02T18:22:35.800962747Z at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2024-08-02T18:22:35.800966548Z code: undefined,
2024-08-02T18:22:35.800970148Z statusCode: 404,
2024-08-02T18:22:35.800973748Z request: WebResource {
2024-08-02T18:22:35.800977348Z streamResponseBody: undefined,
2024-08-02T18:22:35.800980948Z streamResponseStatusCodes: Set(0) {},
2024-08-02T18:22:35.800984648Z url: 'https://appcs-gh-run-controller-infraeng.azconfig.io/kv/azure-github-runners-queue?api-version=1.0',
2024-08-02T18:22:35.800988348Z method: 'GET',
2024-08-02T18:22:35.800991948Z headers: HttpHeaders {
2024-08-02T18:22:35.800995548Z _headersMap: {
2024-08-02T18:22:35.800999149Z accept: {
2024-08-02T18:22:35.801002649Z name: 'Accept',
2024-08-02T18:22:35.801006349Z value: 'application/vnd.microsoft.appconfig.kv+json, application/json, application/problem+json'
2024-08-02T18:22:35.801010049Z },
2024-08-02T18:22:35.801013549Z 'user-agent': {
2024-08-02T18:22:35.801017049Z name: 'User-Agent',
2024-08-02T18:22:35.801020749Z value: 'azsdk-js-app-configuration/1.3.1 core-http/2.2.7 Node/v18.15.0 OS/(x64-Linux-5.15.153.1-2.cm2)'
2024-08-02T18:22:35.801024449Z },
2024-08-02T18:22:35.801043750Z 'x-ms-client-request-id': {
2024-08-02T18:22:35.801047350Z name: 'x-ms-client-request-id',
2024-08-02T18:22:35.801050850Z value: '4c42b171-c122-4142-a43e-da16df7e4b78'
2024-08-02T18:22:35.801054250Z },
2024-08-02T18:22:35.801057650Z authorization: {
2024-08-02T18:22:35.801064250Z name: 'authorization',
2024-08-02T18:22:35.801081751Z value: 'Bearer

**Comment by jburns24** [comment]
Thank you for opening the issue @Adam-McGill, sorry we left this in limbo for so long.

Unfortunately we have decided to archive this repository for the time being. We have shifted attention to other projects and this project is not getting the love and attention it deserves.
